pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CI
  displayName: CI Stage
  jobs:
  - job: build
    displayName: Build and Test
    steps:
    - script: |
        DOCKER_BUILDKIT=1 docker build \
          --target export \
          --output type=local,dest=$(Build.ArtifactStagingDirectory)/publish \
          .
      displayName: 'Build, test and publish in Docker'
    - task: ArchiveFiles@2
      displayName: 'Bundle as .zip'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/whist.zip'
        replaceExistingArchive: true
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/whist.zip'
        artifact: 'drop'
        publishLocation: 'pipeline'
- stage: CD
  displayName: CD Stage
  dependsOn: CI
  # NOTE(jorgen.fogh): Deployment has been switched off until I get a new Azure subscription:
  condition: and(False, succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: deploy
    displayName: Deploy
    environment: jrgfogh
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure App Service'
            inputs:
              azureSubscription: 'jrgfogh-whist - Azure'
              appType: webAppLinux
              appName: 'jrgfogh-whist'
              package: '$(Pipeline.Workspace)/drop/whist.zip'
