pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: CI
  displayName: CI Stage
  jobs:
  - job: build
    displayName: Build and Test
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
      displayName: 'Run tests'
    - task: DotNetCoreCLI@2
      displayName: Bundle as .zip
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: '$(ArtifactName)'
        publishLocation: 'pipeline'
- stage: CD
  displayName: CD Stage
  jobs:
  - deployment: deploy
    displayName: Deploy
    environment: jrgfogh
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy Azure App Service'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'jrgfogh-whist - Azure'
              appType: webAppLinux
              WebAppName: 'jrgfogh-whist'
              RuntimeStack: 'DOTNETCORE|Latest'
              DeploymentType: 'webDeploy'